name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy project
        run: |
          cd /home/vitaz/gl-monitor-demo
          git pull origin main
          docker compose up -d --build